import { createElement } from 'lwc';
import B2_Two_way_binding_prac from 'c/b2_Two_way_binding_prac';

describe('c-b2-two-way-binding-prac', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-b2-two-way-binding-prac', {
            is: B2_Two_way_binding_prac
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});